# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
   schedule:
     - cron: '0 0/12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install lxml
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        #
    # - name: Update MESL
    #   run: |
    #     cd MESL
    #     python MESL_All.py   
    - name: Update tongyong
      run: |
        cd tongyong
        python 1SendEmail_And_regist.py
    - name: Commit
      run: |
        git config --global user.email 953777956@qq.com
        git config --global user.name TryAgainC
        git add .
        #git commit -m"action:`date +'%Y-%m-%d'`"
        git commit -m"action:`date`"
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
